var mongoose = require('mongoose');
var opportunitySchema = mongoose.Schema({
    PrimaryOrganizationId: String,
    CreatedBy: String,
    CreationDate: String,
    CurrencyCode: String,
    SalesMethodId: String,
    SalesStageId: String,
    Description: String,
    LastUpdateDate: String,
    LastUpdatedBy: String,
    LastUpdateLogin: String,
    Name: String,
    OptyId: String,
    OptyNumber: String,
    OwnerResourcePartyId: String,
    PrimaryRevenueId: String,
    SalesMethod: String,
    SalesStage: String,
    DescriptionText: String,
    AverageDaysAtStage: String,
    MaximumDaysInStage: String,
    PhaseCd: String,
    QuotaFactor: String,
    RcmndWinProb: String,
    StageStatusCd: String,
    StgOrder: String,
    EffectiveDate: String,
    Revenue: String,
    WinProb: String,
    SourceType: String,
    PrimaryContactPartyName: String,
    PrimaryContactFormattedPhoneNumber: String,
    PrimaryContactEmailAddress: String,
    Comments: String,
    PartyName1: String,
    EmailAddress: String,
    LookupCategory: String,
    OptyCreationDate: String,
    ExpectAmount: String,
    OptyCreatedBy: String,
    ForecastOverrideCode: String,
    OptyLastUpdateDate: String,
    OptyLastUpdatedBy: String,
    SalesChannelCd: String,
    PredWinProb: String
});
module.exports = mongoose.model('Opportunity',opportunitySchema);